name: Generate Release PDF

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.gitignore'
      - '**/*.md'

jobs:
  release_pdf:
    uses: hooyuser/pdf-ci-templates/.github/workflows/typst-pdf-release.yml@main
    with:
      TYPST_FILE_NAME: algebraic_geometry
